### ISSUE TITLE
Shipping method is not found :- error

### ISSUE THREAD

**Issue by mvjohn100** [freego/spree_simple_weight_calculator#3]
while using branch 1.3-stable  with spree 1.3.2

added to gem file
gem 'spree_simple_weight_calculator', '~> 1.3.0'

while Creating  shipping method,  choose "Simple Weight" as calculator and when update. receive the following error

"Shipping method is not found"

**Comment by alepore** [comment]
I just tried on a new spree 1.3.2 and 1-3-stable apps and had no problems to create a shipping method with "Simple Weight".
Can you provide steps to reproduce on a clean app?

Thanks.
